### ISSUE TITLE
Filter questions based on tags and Single/Multiple choice

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/gru#100]
Clicking on a tag with a question description should filter out other questions with those tags and show only those.
Also maybe we can have another field in question description, which says multiple and can have value True/False. There should be a way to filter out questions which have single/multiple correct options.

**Comment by manishrjain** [comment]
Instead of creating derivative information about True/False, why not filter by count? In any case, this can be done within the frontend easily, particularly, if you retrieve just the tags and the multiple choice status for all questions, and then just filter in the frontend itself.

**Comment by manishrjain** [comment]
Also, another thing I've noticed is that the questions get cached, and if changed by someone else, they don't get updated. Ideally, you want to updated the question cache every time someone views that question by clicking on the pager.

**Comment by pawanrawal** [comment]
Creating another issue for the last comment.

**Comment by manishrjain** [comment]
Also, can you filter by the question title? I think all this filtering could be handled in the frontend.

**Comment by pawanrawal** [comment]
Yup, we filter by question title too now.
