### ISSUE TITLE
Question details should be fetched from the server when clicking on question name.

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/gru#102]
Right now we fetch the question name and details for all questions for the index page. This means that if a user updates the question information then another user can't see the update without a page update.

Ideally, we should just fetch the question name and uids for index and clicking on a question name should trigger another call to the server to fetch details regarding it.

**Comment by manishrjain** [comment]
I'd say retrieve the tags and multiple answer status as well, so you can do filtering from the frontend itself, without incurring further trips to the backend.

**Comment by pawanrawal** [comment]
That makes sense. Thanks for the suggestion @manishrjain.

**Comment by pawanrawal** [comment]
Fixed
