### ISSUE TITLE
Utilize vertical space wisely

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/gru#108]
Right now, we use up too much vertical space in Gru admin panel. These are the 3 factors:

- Gru Admin bar
- List of all questions bar
- Options taking up too much vertical space

Decrease and eliminate these issues, so we can view an entire question and it's options without vertically scrolling.

**Comment by pawanrawal** [comment]
Fixed, please try a hard refresh.

**Comment by pawanrawal** [comment]
Fixed.
