### ISSUE TITLE
Various fixes in "Not Completed" candidates

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/gru#109]
- [x] Show the invitation date in this format: Jan 2, 2006, which is more readable. Allow sorting by it.
- [x] Also, the validity date could be shown as expiring in X days instead.
- [x] Add a link to resend invite.
- [x] Add a link to Cancel invite. 
- [x] Only show candidates with valid invites.

**Comment by pawanrawal** [comment]
Do you think validity date is of any use on this page?

**Comment by manishrjain** [comment]
Maybe. But, we probably do need a way to see the invalid invitations that were never taken -- so we could resend them, if need be.

**Comment by pawanrawal** [comment]
This is done.
