### ISSUE TITLE
Back button.

### ISSUE THREAD

**Issue by pulkitrai** [dgraph-io/gru#112]
When we view the report for the candidate. There is no button to go back to the list of the candidates. We have to use the browser button to go back.

**Comment by pawanrawal** [comment]
Well you anyway have to use a button 😛 . Try `Cmd + <- (left key)` to go back.

**Comment by pulkitrai** [comment]
Would be Convenient to have a small button. :P

Pulkit Rai
https://dgraph.io/
+61469590693
pulkit@dgraph.io

**Comment by manishrjain** [comment]
I think this isn't as important. The back button in the browser is designed for things like these.
