### ISSUE TITLE
Show percentile next to score of candidates

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/gru#115]
For now, we could do this entirely in the front end.

But, later on, as we paginate this list, we should pick the lowest score that we have on the page, and ask Dgraph to give a total count of all valid (not deleted) candidates who took the quiz, and a count of all candidates who got a score < the lowest score on page. This should then be incorporated in the frontend to show the percentile scores.

**Comment by pawanrawal** [comment]
This is done on the frontend for now.

**Comment by manishrjain** [comment]
It's buggy.
![1478866910](https://cloud.githubusercontent.com/assets/1782324/20215015/bf0a04f0-a865-11e6-8b4d-42b4e59d2b0d.png)

**Comment by pawanrawal** [comment]
Hey, sorry for the poor user experience. Please check now. Also updated it so that it takes into account deleted candidates too (which we anyway soft-delete).

**Comment by manishrjain** [comment]
Thanks for fixing. Also, shouldn't the top candidate be 100%-ile?

**Comment by pawanrawal** [comment]
It is 100%-ile now. It wasn't so earlier because of the dummy quizzes take by Pulkit and the team. I have  deleted those dummy quizzes. Also rounded of to the floor value as that should be good enough for our use case.

**Comment by manishrjain** [comment]
Tamer now has the percentile to 2%, even though he's the lowest scoring candidate. Also, quizzes shouldn't affect each other. Percentile should be per quiz.

**Comment by pawanrawal** [comment]
It is per quiz right now. The way the percentile is calculated is

```
(No. of having score <= value) / Total Number of candidates * 100
```
For Tamer it is 1/50 * 100. We could make that a strict inequality(<), which would make the lowest scoring candidate have 0%-le but the highest scoring candidate won't have 100% then.

**Comment by manishrjain** [comment]
Ah.. I see. That makes sense. Thanks for clarifying.
