### ISSUE TITLE
Show number of questions yet to be answered

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/gru#118]
Two highest scoring candidates in our quiz, both had this to say:

> I was fun quiz to close. 
> Showing the number of questions yet to be answered in the quiz would have helped me not skip a few questions. I skipped a couple of questions, I thought I was running out of time but I still had enough time to go through them.

And,

> This is very interesting quiz.
> One feedback is to let participant knows how many questions left and how many points left. This helps participant to decide how much time he/she should work on each question.

While I was initially against showing the number of questions, or score left, I think both options make sense to let people better manage their time. Also, with the 2 min skip blocking helps ensure that there is certain penalty associated with skipping questions -- so I feel more confident with showing the candidates how much time and score they have left.

**Comment by pawanrawal** [comment]
We show the total number of questions and the current question number above the question text like

`Question 1 of 29`

The backend sends information about the total score left too but couldn't think of an appropriate place to display it on the frontend. I don't want to clutter the top bar. Also, I personally feel we shouldn't maybe burden the candidate with another piece of information. Maybe we can display the max possible score on the first screen. Thoughts @manishrjain?

**Comment by manishrjain** [comment]
I think each info in our top bar uses up too much horizontal space by being fancy. We can simplify all that to add more information there.

Having said that, I don't have a strong opinion -- this is something that a couple of candidates asked for. If you don't think it's helpful, feel free to skip. Just showing Q 1 of 29 etc. is sufficient for now.

**Comment by pawanrawal** [comment]
I pushed out the change about showing the number of questions. I'd say let's wait sometime, if people still ask for the total score left then we'd find a way to show it.

**Comment by manishrjain** [comment]
Sounds good. Closing the issue.
