### ISSUE TITLE
Resend link doesn't update expiry date

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/gru#123]
For not completed quiz which got expired, clicking on resend doesn't automatically extend the expiry date by 7 days. We basically send out the same expired link, from what I understand.

**Comment by pawanrawal** [comment]
Ok, so the resend link and validity are two different things. Resend is more for the case when say the candidate for some reason didn't receive the link/email changed. Though I think we can be smarter and check that if the validity has expired then automatically extend it. I will make this change.

**Comment by pawanrawal** [comment]
This is done.

**Comment by manishrjain** [comment]
If you resend with just one day left, it doesn't help much. I think to keep things simple, every time you resend, it should just extend by another week.

**Comment by pawanrawal** [comment]
Ok, I will extend it by a week from **now** everytime you resend.

**Comment by pawanrawal** [comment]
This is done.
