### ISSUE TITLE
Clicking on last question in pager doesn't show blue bg

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/gru#128]
The last question in candidate report, for e.g.
https://gru.dgraph.io/#/admin/invite/candidate-report/0x6638fda41158e1c

If you select the last question in the pager on the left, it doesn't render the question selected blue. While it doesn't affect the functionality, it looks like a bug.

**Comment by pawanrawal** [comment]
This was an interesting bug. Thanks for reporting. Actually, the last question wasn't visible in the sidebar. It is now.

**Comment by pawanrawal** [comment]
Looks like I mixed two bugs. The last question wasn't visible earlier, which is visible now. Looking at this now.

**Comment by pawanrawal** [comment]
Fixed for good now.
