### ISSUE TITLE
Remove total score, add percentile in candidate report

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/gru#129]
It looks like total score in candidate report doesn't take into account the skipped questions. The total score should be based on that. However, total score doesn't make much sense anyway, because this is competitive system, and percentiles are lot more important. In fact, we don't show percentiles in the report, which we should.

**Comment by pawanrawal** [comment]
We do take the skipped questions into account. 

Okay, I will remove the total score and add percentile to the candidate report page.

**Comment by pawanrawal** [comment]
We show percentile now as part of the circle which showed the score earlier.

**Comment by pawanrawal** [comment]
I think this requires a bit more work. Since we share the report the percentile information would have to be calculated on the backend.

**Comment by manishrjain** [comment]
We can't do inequality right now, can we? If we could, you could ask for
count of candidates with score less than equals self. Maybe ask Ashwin to
build that.

**Comment by pawanrawal** [comment]
@jchiu0 is working on this. For now, I will calculate this on the backend and send it.

**Comment by pawanrawal** [comment]
This is done and deployed.
