### ISSUE TITLE
Ability to upload resume in GRU

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/gru#133]
When a candidate does well, I find myself looking for their resume. But the system doesn't support having one. When inviting the candidates, there should be a way to upload their resume as well; which can be downloaded from their report.

We can have the resumes be uploaded to S3; so we don't have to store them.

**Comment by pawanrawal** [comment]
That sounds useful though I wonder how that would play out with our current invite page as we allow simultaneously inviting multiple candidates. We have the following options. 

1. We move back to the ability to just invite one candidate and make uploading the resume compulsory? 2. We can allow adding the resume as part of the Edit page but then no one would do it before the candidate takes the test.
3. We ask the candidate to upload his resume before starting the test. Convenient to us but not sure how convenient it is to the candidate.

**Comment by manishrjain** [comment]
Yeah, maybe invite one candidate at a time makes sense. Also, make uploading resume optional. Ideally, there's a way to also update/upload resume from the report page.

**Comment by pawanrawal** [comment]
Sure, since we are making resume uploading optional, I think we can have two options. 
1. Bulk Invite (to invite candidates we don't have the resume for using their email), 
2. Other for inviting a single candidate with or without the resume.

**Comment by manishrjain** [comment]
@pulkitrai thinks it's best that the candidates upload their resume when they start taking the quiz. We can make it optional; but recommended. That way, we can still have the bulk invite; and the whole effort won't have to be done by a single person.

**Comment by pawanrawal** [comment]
Cool, let's try this.

**Comment by pawanrawal** [comment]
This is done and deployed. Took a while. If candidates upload their resume, we can view it from the report page.
