### ISSUE TITLE
Error while parsing time for the re-sent invite link

### ISSUE THREAD

**Issue by prashant-shahi** [dgraph-io/gru#156]
### Screenshot

![](https://gist.githubusercontent.com/prashant-shahi/53cd2552e7a0b5e546ff78e083155d34/raw/2a697405943e5ed4d627ea43459062260908e4c3/screenshot.jpg)

### Steps to reproduce
- Send an invite to an email id.
- Resend the invite.
- Open the invite link that is received.

**Comment by danielmai** [comment]
A workaround for now:
- Cancel the invite
- Re-send a new invite. Do not try to re-send another invite after recreating the invite.
