### ISSUE TITLE
Have a limit on the maximum number of skips in a row.

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/gru#18]
The objective here is to have the option to set a limit to the maximum number of skips possible without answering a question.

**Comment by mohitranka** [comment]
@dgraph-io/team Picking up this issue, but it is going to take me couple of days likely, as I need to understand existing codebase.

**Comment by pawanrawal** [comment]
Sure, play around with it. Would love to know what you like/dislike about it?

**Comment by pawanrawal** [comment]
Closing this for now as the candidate can't skip before two minutes for now.
