### ISSUE TITLE
Problem with updating tags while updating Question

### ISSUE THREAD

**Issue by Rahul-Sagore** [dgraph-io/gru#48]
Problem occurs when on "Question Update UI", and update the tags.
When try to add/remove single tag in one updation, it work perfectly.

But if I remove existing tag and add new tag in one updation, I got successful response, but then Dgraph server stops with error (While hitting api for getting tags and question):
```
2016/10/07 09:42:02 lists.go:169: Dirty map size: 3
2016/10/07 09:42:02 list.go:701: Idx: 0. Unable to parse posting.
```

This was the delete mutation for removing existing relationship of tag with question, where 0x950d84987a78b56c is question's uid:

```
mutation { 
  delete { 
     <_uid_:0x950d84987a78b56c> <question.tag> <_uid_:0x52408512122d7951> .
     <_uid_:0x52408512122d7951> <tag.question> <_uid_:0x950d84987a78b56c> .
   }
}
```

This was the final mutation, associating new tag in last line
```
mutation {
      set {
          <_uid_:0x950d84987a78b56c> <text> "This%20is%20the%20formatter%20question%0A%0Avar%20i%20%3D%200%3B" .
          <_uid_:0x950d84987a78b56c> <positive> "1" .
          <_uid_:0x950d84987a78b56c> <negative> "-0.6" .
           <_uid_:0x7e4f97a6b71ecbec> <name> "adad" .
          <_uid_:0x950d84987a78b56c> <question.option> <_uid_:0x7e4f97a6b71ecbec> .
          <_uid_:0xc70bd4baf809b546> <name> "fsf" .
          <_uid_:0x950d84987a78b56c> <question.option> <_uid_:0xc70bd4baf809b546> .
          <_uid_:0xc729345cc6c937d5> <name> "fsf" .
          <_uid_:0x950d84987a78b56c> <question.option> <_uid_:0xc729345cc6c937d5> .
          <_uid_:0xdae6aa3f1df3d4db> <name> "fs" .
          <_uid_:0x950d84987a78b56c> <question.option> <_uid_:0xdae6aa3f1df3d4db> .
          <_uid_:0x950d84987a78b56c> <question.correct> <_uid_:0xdae6aa3f1df3d4db> .
          <_uid_:0x950d84987a78b56c> <question.tag> <_uid_:0xc0e1495c836bc87e> .
         <_uid_:0xc0e1495c836bc87e> <tag.question> <_uid_:0x950d84987a78b56c> .
     }
}
```

Need to debug this.

Steps to reproduce from UI:

1. Add question with one tag associated to it.
2. Go to edit question page, remove the associated tag, add new tag. 
3. Click on update button. You will get response "Successfully updated".
4. Try to access "Show all Question", Dgraph will stop/ or will give error.

**Comment by pawanrawal** [comment]
Can you also update the thread with the mutation that you are trying to run?
