### ISSUE TITLE
Support for viewing candidate report

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/gru#51]
View candidates page should have the option to view the candidate report for candidates who have taken the test.

**Comment by pawanrawal** [comment]
I have made the changes to the API.

1. `/admin/candidates` also returns a complete field for each candidate indicating if they successfully completed the test or not. If it is true, then the Candidates index page should have an option to view candidate report.
2. `/admin/candidate/report/:id` would return the data to show a report for the candidates who successfully completed the test. This should be rendered with a summary and a detailed report.

**Comment by pawanrawal** [comment]
For a non-logged in user, this should redirect to login page. Right now just displays an empty page. Same for all admin pages.
https://gru.dgraph.io/#/admin/invite/candidate-report/0xe8f5e10020c71802

**Comment by Rahul-Sagore** [comment]
Yes, this has been fixed. Have not pushed it yet.

**Comment by pawanrawal** [comment]
This is done.
