### ISSUE TITLE
Send quiz duration in appropriate format

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/gru#52]
The quiz duration and any durations for that matter should be sent in a format understandable by the backend.

This https://github.com/icholy/Duration.js/tree/golang_compatible should do the job and would save you some time at the cost of adding a dependency. We can start with this and replace this later.

**Comment by Rahul-Sagore** [comment]
This is done.

**Comment by Rahul-Sagore** [comment]
This is Done
