### ISSUE TITLE
Correct spelling mistakes

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/gru#54]
1. Add/Edit question, spelling of `Positive`. Also call it `Positive Score` maybe.

2. Pagination, spelling of `questions` in No more questions.

**Comment by Rahul-Sagore** [comment]
This is done.

**Comment by pawanrawal** [comment]
Can only see No. 2 as being done. Did you do No. 1 too?

**Comment by Rahul-Sagore** [comment]
Yes, https://github.com/dgraph-io/gru/commit/3febd0a51e93d4d1221c191c156b3fa8a08a41a3

**Comment by Rahul-Sagore** [comment]
This is Done.
