### ISSUE TITLE
Empty aid sent in Answer API for multiple choice qns

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/gru#59]
I logged the `aid` received. For questions with multiple answers, it is empty. It should be a comma separated string of answer id's. Please check.

**Comment by Rahul-Sagore** [comment]
This has been fixed.

I was sending multiple answer id, but it was in form of array. Changed it to comma separated string.

**Comment by pawanrawal** [comment]
Verified this has been fixed.
