### ISSUE TITLE
Wrong routes hit when user logged into Admin panel tries to take the quiz

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/gru#62]
If a user is logged into the Admin panel and tries to take the quiz using the link, wrong routes are hit and we get Something Went Wrong error while taking the quiz.

**Comment by Rahul-Sagore** [comment]
This has been fixed.

**Comment by pawanrawal** [comment]
Verified it works if the user is logged in. Though now I see I am logged out everytime I restart gruadmin server. Whats the change here?
