### ISSUE TITLE
Clean up edit candidate API

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/gru#65]
From candidate invite add/edit view, we should allow only one quiz to be selected.
If same candidate has to be invited to multiple quizzes, we can create multiple invites and shouldn't do this within the same invite for now.

Candidate Edit API should send non-empty old_quiz_id and quiz_id only if quiz which the candidate is invited to is changed. If quiz was not changed, then both should be empty.

**Comment by Rahul-Sagore** [comment]
This is done.
