### ISSUE TITLE
Show error to user if Ping API doesn't respond for 30 secs

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/gru#69]
In case the server crashes, Ping API won't be respond. We should stop the user and let him know that something is wrong and that he should contact Dgraph.

**Comment by Rahul-Sagore** [comment]
This is done. Currently tested on frontend by timing out api call with 2ms. Need to test with real case.
Need to see how we will convey the message to the candidate. Currently I have designed a custom modal window component for displaying message. This component is general, can be used for other cases also.

**Comment by pawanrawal** [comment]
Cool, atleast conveys the message to the user. How about making the background transparent so that the user can't see the question anymore?

**Comment by Rahul-Sagore** [comment]
Currently I am display a message in modal window saying that "something went wrong, contact dgraph" (If you haven't seen that modal window then must be cashing issue.). 
Just wanted to know what should be the behaviour of quiz, when ping API timeouts. I'll stop the quiz.

**Comment by pawanrawal** [comment]
We can talk about the correct way to go about this.

**Comment by pawanrawal** [comment]
So the way we should implement this is that

1. Let's change ping duration to 3 secs. If two consecutive pings don't return 200, display a message on the top that `Can't connect to the server. We will be back up in a bit` with a red background. User should still be able to see the question and options.
2. Ideally, server won't be down for more than 10 secs, so you should get a 200 OK ping, when you do update the message to show in green background that `Connected to Server`.
3. If you receive no pings for a minute, stop the test and show to the user that we are facing some severe problems and that he should contact contact@dgraph.io.
4. Another related point is that you should retry the getQuestion and sendAnswer API after the server is up for a minute in case it crashed before receiving your request.

**Comment by pawanrawal** [comment]
Done.
