### ISSUE TITLE
Take user directly to questions page in case candidate has already started the quiz.

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/gru#70]
In the case that the client crashed or the candidate closed the browser and tries to restart the quiz, `/validate` API would return `quiz_started` as true. In this case, instructions screen shouldn't be shown, next question should be fetched and shown.

**Comment by Rahul-Sagore** [comment]
This is done.

**Comment by pawanrawal** [comment]
Looks fine. Closing this.
