### ISSUE TITLE
End test when ping returns timeLeft < 0.

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/gru#71]
The test should be ended when ping returns timeLeft < 0. Right now the timeLeft becomes negative and the test continues. 👎

**Comment by Rahul-Sagore** [comment]
Fixed the issue for ending quiz when receiving negative time.

**Comment by pawanrawal** [comment]
Works thanks. Just to make sure the condition should be timeLeft <= 0. Feel free to close if you have handled the == case.

**Comment by Rahul-Sagore** [comment]
Yup handled it.
