### ISSUE TITLE
Time taken on final screen should be total time taken.

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/gru#72]
Time taken on final screen shouldn't just be the time taken for the final question. It should be the total time taken in the test. You could potentially store the duration of the quiz the first time the validate API call is made and use that to calculate the time left.

Also, we don't need to show timeleft.

**Comment by Rahul-Sagore** [comment]
Removed time left.
Total time taken was already implemented. Probably cached issue. Need to verify from your side.
Otherwise this is done.
