### ISSUE TITLE
Hamburger button shouldn't be visible to candidate

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/gru#74]
Hamburger button for Menu (Gru Admin) shouldn't be visible to a candidate taking the quiz.

**Comment by pawanrawal** [comment]
Also if the user is logged in, he should be redirected to Dashboard when going to `/`.

**Comment by pawanrawal** [comment]
Actually we don't the hamburger menu, as it has repeated links. Infact we have three places with the links for Questions and Quiz

1. Hamburger Menu (should get rid of this).
2. Top navbar
3. Dashboard

**Comment by Rahul-Sagore** [comment]
This is done.
