### ISSUE TITLE
Flicker on gru.dgraph.io

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/gru#77]
When I am not logged in and I go to gru.dgraph.io, before the login screen is shown a page with a blue navbar is rendered and then the login page is rendered.

When I am already logged in, the login page is rendered and then within a second the dashboard is rendered which again produces a flicker effect. 

The correct page is rendered very quickly but still it makes for a weird output so we should correct this.

**Comment by Rahul-Sagore** [comment]
This has been fixed
