### ISSUE TITLE
No redirect to login on 401

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/gru#83]
When I try to access the admin panel, the API calls receive a 401, but the UI doesn't redirect to login screen.

**Comment by Rahul-Sagore** [comment]
Is this happening? Unable to reproduce. Any specific url on which it is causing problem?

**Comment by pawanrawal** [comment]
So this was happening if I changed the secret key on the backend. Steps to reproduce. 
1. Login to admin panel. Go to questions index page.
2. Change the value of the secret flag used for starting Gru. 
3. Refresh the questions index page.

What happens is that if the user is logged in, the front end has a token which now becomes invalid and all requests for say get question etc return a 401. In these cases, the token should be invalidated and user should be asked to login again.

**Comment by manishrjain** [comment]
There's a simple way to reproduce this. Open two windows of gru.dgraph.io. Logout from one. The other one is now unresponsive. It would do *nothing*.

**Comment by Rahul-Sagore** [comment]
It was redirecting me to login page, clicking on link on "Other window".

I reproduced it by sending invalid admin token from frontend. So it has been fixed. Need to merge the change.

**Comment by pawanrawal** [comment]
This has been deployed.
