### ISSUE TITLE
Wait for 2 mins before allowing a skip

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/gru#86]
I've noticed that candidates tend to skip all or most questions from a topic that they don't like. This is a bad practise, because it makes us hard to judge them. Skipping should be allowed only to skip certain questions which they really are having a hard time with, not to escape a complete topic.

Having a X mins, say X = 2 or whatever else seems fit, lag before we allow a question to be skipped would be a good way to ensure that the candidate is spending a considerable time thinking through a question, instead of blindly skipping it. Note that they are not supposed to control the flow of the questions, our system does. And if we're showing a question, we expect the candidate to try to solve it.

**Comment by manishrjain** [comment]
Seeing more candidates skip questions they don't like -- which then makes the process of eliminating them, manual. Once you look at the report, you'll see obvious gap holes in knowledge in a certain category. Having the candidate think through the question for at least 2 mins, is a good way to avoid that; and also helps us judge their knowledge in every category better.

**Comment by pawanrawal** [comment]
This is merged and is live now.
