### ISSUE TITLE
Bulk Invites

### ISSUE THREAD

**Issue by pulkitrai** [dgraph-io/gru#88]
At the moment we have to add the name and the email id one by one. There should be provision to add the email ids in bulk without being asked for the name and the name should be picked up automatically likewise hackerrank

**Comment by pawanrawal** [comment]
@pulkitrai I just wanted to check if it is still useful since we only have to add the email now to invite a candidate?

**Comment by pulkitrai** [comment]
@pawanrawal  ya would be more convenient.

**Comment by pawanrawal** [comment]
You have it now @pulkitrai.

**Comment by pulkitrai** [comment]
Thanks :)


Pulkit Rai
https://dgraph.io/
+61469590693
pulkit@dgraph.io
