### ISSUE TITLE
Candidate Name 

### ISSUE THREAD

**Issue by pulkitrai** [dgraph-io/gru#89]
When we send an invitation it asks for the candidate name. It is a mandatory field. Sometimes we do not have the name of the candidate. Can we remove it from the mandatory field?

**Comment by manishrjain** [comment]
Also, to update the bug: Ask name from the candidate at the beginning of the quiz, and use that name everywhere, including in reports.

**Comment by pawanrawal** [comment]
Fixed, we ask it from the candidate now before he can start the quiz.
