### ISSUE TITLE
Make the front-end responsive.

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/gru#90]
The admin panel and specially the actual quiz, should ideally work on a mobile phone too.

**Comment by pawanrawal** [comment]
Quiz has been made responsive. @Rahul-Sagore I think we don't need to add the functionality for adding the actual quiz question for anything less than a Desktop. Though sending invite should be possible even from a mobile.

**Comment by Rahul-Sagore** [comment]
Okay, Will check responsiveness of invite candidate. and will check other pages also (If takes less time to make them responsive).

**Comment by pawanrawal** [comment]
Thanks for making the invite quiz page responsive.
