### ISSUE TITLE
Have a way to send emails to candidates from Admin panel

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/gru#99]
About the decision, and possibly some feedback from their quiz, based on our tagging system. The feedback should be optional, that we only send for candidates who just missed the mark.

Also, would be useful to have a way to resend invitations, etc.

**Comment by pawanrawal** [comment]
@pulkitrai Am I right we only want to have it for candidates who we want to reject? I can also set it up in a way so that these candidates are also automatically deleted when we send them a reject mail

**Comment by pulkitrai** [comment]
@pawanrawal It would be helpful if they would be automatically deleted or candidates below 55 the system can delete or send them rejection automatically.

**Comment by manishrjain** [comment]
Please don't delete any data or candidates from the system. This is the only way for us to gauge the percentiles, and compare candidates. We just need a way to reject them easily. Ideally, one could set a threshold from the admin panel, and all the candidates who got a score less than that, can automatically get a rejection mail, with join@dgraph.io BCCed.

**Comment by pawanrawal** [comment]
That sounds good. I am wondering if we can just use the quiz screen to tell them that we are not going to proceed as they didn't cross the threshold or should we send a mail?

**Comment by manishrjain** [comment]
I think an email is better, because in case they need to follow up, they'll have a way to get to us easily, via join@dgraph.io.

**Comment by pawanrawal** [comment]
We send an email to the candidate after 1 hour if his score <= 70 (configurable from panel) right now. This happens via a goroutine which sleeps for 1 hour.

The only problem is that if we deploy new code and hence restart the server, pending goroutines would get canceled. Solution to this might be storing this information in Dgraph and whenever the Gru server boots up it loads up this information about who to send rejection mail's to and when.

**Comment by manishrjain** [comment]
You could have a special node, and add an edge for the rejected candidate. Run a goroutine every 10 mins or so, and look for edges in this. If it's been an hour since write, then send off the email and delete the edge. This would survive crashes and restarts.

**Comment by pawanrawal** [comment]
Thanks for the idea @manishrjain. This is done.
